import './globals.css';
import './normailze.css';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider, Layout } from 'antd';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { customMenuToken } from '@/asset/antd/antd-set';
import style from '@/asset/css/main-layout.module.css';
import Header from '@/components/main-header';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ko'>
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				<AntdRegistry>
					<ConfigProvider
						theme={{
							components: {
								Menu: customMenuToken,
							},
						}}
					>
						<Layout className={style.main_layout}>
							<Header />
							<main className={style.main_warp}>{children}</main>
							<footer className={style.main_footer}>SEO GENERATOR ©{new Date().getFullYear()} Created by H.B</footer>
						</Layout>
					</ConfigProvider>
				</AntdRegistry>
			</body>
		</html>
	);
}
