import './globals.css';
import './normailze.css';

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { App, ConfigProvider, Layout } from 'antd';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { customMenuToken } from '@/asset/antd/antd-set';
import c_style from '@/asset/css/custom.module.css';
import style from '@/asset/css/main-layout.module.css';
import Header from '@/components/main-header';
import SubTitle from '@/components/sub-title';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ko'>
			<body className={`${geistSans.variable} ${geistMono.variable}`} style={{ minWidth: '320px' }}>
				<AntdRegistry>
					<ConfigProvider
						theme={{
							components: {
								Menu: customMenuToken,
							},
						}}
					>
						<Layout className={style.main_layout}>
							<Header header_title='SEO Tag Generator' />
							<main className={style.main_warp}>
								<div className={c_style.main_title}>
									<SubTitle mainText='SEO Tag Generator' subText='Generate SEO meta tag for your website' />
								</div>
								<App>{children}</App>
							</main>
							<footer className={style.main_footer}>SEO GENERATOR ©{new Date().getFullYear()} Created by H.B</footer>
						</Layout>
					</ConfigProvider>
				</AntdRegistry>
			</body>
		</html>
	);
}
